var searchData=
[
  ['handle',['Handle',['../structUtilities_1_1CUDA_1_1Handle.html',1,'Utilities::CUDA']]],
  ['hangingnodes',['HangingNodes',['../classCUDAWrappers_1_1internal_1_1HangingNodes.html',1,'CUDAWrappers::internal']]],
  ['has_5fbegin_5fand_5fend',['has_begin_and_end',['../classhas__begin__and__end.html',1,'']]],
  ['has_5fget_5fmpi_5fcommunicator',['has_get_mpi_communicator',['../structinternal_1_1LinearOperatorImplementation_1_1ReinitHelper_3_01LinearAlgebra_1_1distributed_4a1282d020cabbaffebe5b90bd62626f.html',1,'internal::LinearOperatorImplementation::ReinitHelper&lt; LinearAlgebra::distributed::Vector&lt; Number &gt; &gt;']]],
  ['has_5finitialize_5fdof_5fvector',['has_initialize_dof_vector',['../structinternal_1_1LinearOperatorImplementation_1_1ReinitHelper_3_01LinearAlgebra_1_1distributed_8ff2d397caecf464466c13ccb129a90d.html',1,'internal::LinearOperatorImplementation::ReinitHelper&lt; LinearAlgebra::distributed::Vector&lt; Number &gt; &gt;']]],
  ['has_5flocally_5fowned_5fdomain_5findices',['has_locally_owned_domain_indices',['../structinternal_1_1LinearOperatorImplementation_1_1ReinitHelper_3_01LinearAlgebra_1_1distributed_67b8e913192f170b93a7d6978fef4153.html',1,'internal::LinearOperatorImplementation::ReinitHelper&lt; LinearAlgebra::distributed::Vector&lt; Number &gt; &gt;']]],
  ['has_5flocally_5fowned_5frange_5findices',['has_locally_owned_range_indices',['../structinternal_1_1LinearOperatorImplementation_1_1ReinitHelper_3_01LinearAlgebra_1_1distributed_a829601ff1c9c5ad3f8c378622c2df1c.html',1,'internal::LinearOperatorImplementation::ReinitHelper&lt; LinearAlgebra::distributed::Vector&lt; Number &gt; &gt;']]],
  ['has_5fvector_5finterface',['has_vector_interface',['../classinternal_1_1PackagedOperationImplementation_1_1has__vector__interface.html',1,'internal::PackagedOperationImplementation']]],
  ['has_5fvmult_5fadd_5fand_5ftvmult_5fadd',['has_vmult_add_and_Tvmult_add',['../classinternal_1_1LinearOperatorImplementation_1_1has__vmult__add__and__Tvmult__add.html',1,'internal::LinearOperatorImplementation']]],
  ['hasrequiredadinfo',['HasRequiredADInfo',['../structDifferentiation_1_1AD_1_1internal_1_1HasRequiredADInfo.html',1,'Differentiation::AD::internal']]],
  ['helper',['Helper',['../structColorEnriched_1_1Helper.html',1,'ColorEnriched']]],
  ['helperbase',['HelperBase',['../classDifferentiation_1_1AD_1_1HelperBase.html',1,'Differentiation::AD']]],
  ['hermiteinterpolation',['HermiteInterpolation',['../classPolynomials_1_1HermiteInterpolation.html',1,'Polynomials']]],
  ['hermitelikeinterpolation',['HermiteLikeInterpolation',['../classPolynomials_1_1HermiteLikeInterpolation.html',1,'Polynomials']]],
  ['hessiantype',['HessianType',['../structDifferentiation_1_1AD_1_1internal_1_1HessianType.html',1,'Differentiation::AD::internal']]],
  ['hessiantype_3c_20fevaluesextractors_3a_3ascalar_2c_20fevaluesextractors_3a_3asymmetrictensor_3c_202_20_3e_20_3e',['HessianType&lt; FEValuesExtractors::Scalar, FEValuesExtractors::SymmetricTensor&lt; 2 &gt; &gt;',['../structDifferentiation_1_1AD_1_1internal_1_1HessianType_3_01FEValuesExtractors_1_1Scalar_00_01FEV29da66e3a12fe81bc637f7a53e31d995.html',1,'Differentiation::AD::internal']]],
  ['hessiantype_3c_20fevaluesextractors_3a_3asymmetrictensor_3c_202_20_3e_2c_20fevaluesextractors_3a_3ascalar_20_3e',['HessianType&lt; FEValuesExtractors::SymmetricTensor&lt; 2 &gt;, FEValuesExtractors::Scalar &gt;',['../structDifferentiation_1_1AD_1_1internal_1_1HessianType_3_01FEValuesExtractors_1_1SymmetricTensor1fcc01f5160dd02c8dce75aa519a71c5.html',1,'Differentiation::AD::internal']]],
  ['hessiantype_3c_20fevaluesextractors_3a_3asymmetrictensor_3c_202_20_3e_2c_20fevaluesextractors_3a_3asymmetrictensor_3c_202_20_3e_20_3e',['HessianType&lt; FEValuesExtractors::SymmetricTensor&lt; 2 &gt;, FEValuesExtractors::SymmetricTensor&lt; 2 &gt; &gt;',['../structDifferentiation_1_1AD_1_1internal_1_1HessianType_3_01FEValuesExtractors_1_1SymmetricTensor53e75a7bea61297f7f3bd95fe09ad3ea.html',1,'Differentiation::AD::internal']]],
  ['hierarchical',['Hierarchical',['../classPolynomials_1_1Hierarchical.html',1,'Polynomials']]],
  ['histogram',['Histogram',['../classHistogram.html',1,'']]],
  ['host',['Host',['../structMemorySpace_1_1Host.html',1,'MemorySpace']]],
  ['householder',['Householder',['../classHouseholder.html',1,'']]],
  ['householder_3c_20inverse_5ftype_20_3e',['Householder&lt; inverse_type &gt;',['../classHouseholder.html',1,'']]],
  ['householder_3c_20inversenumbertype_20_3e',['Householder&lt; InverseNumberType &gt;',['../classHouseholder.html',1,'']]]
];
