var searchData=
[
  ['handle',['Handle',['../structUtilities_1_1CUDA_1_1Handle.html',1,'Utilities::CUDA']]],
  ['hangingnodes',['HangingNodes',['../classCUDAWrappers_1_1internal_1_1HangingNodes.html',1,'CUDAWrappers::internal']]],
  ['has_5fbegin_5fand_5fend',['has_begin_and_end',['../classhas__begin__and__end.html',1,'']]],
  ['has_5fget_5fmpi_5fcommunicator',['has_get_mpi_communicator',['../structinternal_1_1LinearOperatorImplementation_1_1ReinitHelper_3_01LinearAlgebra_1_1distributed_4a1282d020cabbaffebe5b90bd62626f.html',1,'internal::LinearOperatorImplementation::ReinitHelper&lt; LinearAlgebra::distributed::Vector&lt; Number &gt; &gt;']]],
  ['has_5finitialize_5fdof_5fvector',['has_initialize_dof_vector',['../structinternal_1_1LinearOperatorImplementation_1_1ReinitHelper_3_01LinearAlgebra_1_1distributed_8ff2d397caecf464466c13ccb129a90d.html',1,'internal::LinearOperatorImplementation::ReinitHelper&lt; LinearAlgebra::distributed::Vector&lt; Number &gt; &gt;']]],
  ['has_5fiterator_5fcat',['has_iterator_cat',['../structmystl_1_1has__iterator__cat.html',1,'mystl']]],
  ['has_5fiterator_5fcat_5fof',['has_iterator_cat_of',['../structmystl_1_1has__iterator__cat__of.html',1,'mystl']]],
  ['has_5fiterator_5fcat_5fof_3c_20iter_2c_20bidirectional_5fiterator_5ftag_20_3e',['has_iterator_cat_of&lt; Iter, bidirectional_iterator_tag &gt;',['../structmystl_1_1has__iterator__cat__of.html',1,'mystl']]],
  ['has_5fiterator_5fcat_5fof_3c_20iter_2c_20forward_5fiterator_5ftag_20_3e',['has_iterator_cat_of&lt; Iter, forward_iterator_tag &gt;',['../structmystl_1_1has__iterator__cat__of.html',1,'mystl']]],
  ['has_5fiterator_5fcat_5fof_3c_20iter_2c_20input_5fiterator_5ftag_20_3e',['has_iterator_cat_of&lt; Iter, input_iterator_tag &gt;',['../structmystl_1_1has__iterator__cat__of.html',1,'mystl']]],
  ['has_5fiterator_5fcat_5fof_3c_20iter_2c_20output_5fiterator_5ftag_20_3e',['has_iterator_cat_of&lt; Iter, output_iterator_tag &gt;',['../structmystl_1_1has__iterator__cat__of.html',1,'mystl']]],
  ['has_5fiterator_5fcat_5fof_3c_20iter_2c_20random_5faccess_5fiterator_5ftag_20_3e',['has_iterator_cat_of&lt; Iter, random_access_iterator_tag &gt;',['../structmystl_1_1has__iterator__cat__of.html',1,'mystl']]],
  ['has_5fiterator_5fcat_5fof_3c_20t_2c_20u_2c_20false_20_3e',['has_iterator_cat_of&lt; T, U, false &gt;',['../structmystl_1_1has__iterator__cat__of_3_01T_00_01U_00_01false_01_4.html',1,'mystl']]],
  ['has_5flocally_5fowned_5fdomain_5findices',['has_locally_owned_domain_indices',['../structinternal_1_1LinearOperatorImplementation_1_1ReinitHelper_3_01LinearAlgebra_1_1distributed_67b8e913192f170b93a7d6978fef4153.html',1,'internal::LinearOperatorImplementation::ReinitHelper&lt; LinearAlgebra::distributed::Vector&lt; Number &gt; &gt;']]],
  ['has_5flocally_5fowned_5frange_5findices',['has_locally_owned_range_indices',['../structinternal_1_1LinearOperatorImplementation_1_1ReinitHelper_3_01LinearAlgebra_1_1distributed_a829601ff1c9c5ad3f8c378622c2df1c.html',1,'internal::LinearOperatorImplementation::ReinitHelper&lt; LinearAlgebra::distributed::Vector&lt; Number &gt; &gt;']]],
  ['has_5fvector_5finterface',['has_vector_interface',['../classinternal_1_1PackagedOperationImplementation_1_1has__vector__interface.html',1,'internal::PackagedOperationImplementation']]],
  ['has_5fvmult_5fadd_5fand_5ftvmult_5fadd',['has_vmult_add_and_Tvmult_add',['../classinternal_1_1LinearOperatorImplementation_1_1has__vmult__add__and__Tvmult__add.html',1,'internal::LinearOperatorImplementation']]],
  ['hash',['hash',['../structmystl_1_1hash.html',1,'mystl']]],
  ['hash_3c_20basic_5fstring_3c_20chartype_2c_20chartraits_20_3e_20_3e',['hash&lt; basic_string&lt; CharType, CharTraits &gt; &gt;',['../structmystl_1_1hash_3_01basic__string_3_01CharType_00_01CharTraits_01_4_01_4.html',1,'mystl']]],
  ['hash_3c_20double_20_3e',['hash&lt; double &gt;',['../structmystl_1_1hash_3_01double_01_4.html',1,'mystl']]],
  ['hash_3c_20float_20_3e',['hash&lt; float &gt;',['../structmystl_1_1hash_3_01float_01_4.html',1,'mystl']]],
  ['hash_3c_20long_20double_20_3e',['hash&lt; long double &gt;',['../structmystl_1_1hash_3_01long_01double_01_4.html',1,'mystl']]],
  ['hash_3c_20t_20_2a_20_3e',['hash&lt; T * &gt;',['../structmystl_1_1hash_3_01T_01_5_01_4.html',1,'mystl']]],
  ['hashtable',['hashtable',['../classmystl_1_1hashtable.html',1,'mystl']]],
  ['hashtable_3c_20key_2c_20hash_2c_20keyequal_20_3e',['hashtable&lt; Key, Hash, KeyEqual &gt;',['../classmystl_1_1hashtable.html',1,'mystl']]],
  ['hashtable_3c_20mystl_3a_3apair_3c_20const_20key_2c_20t_20_3e_2c_20hash_2c_20keyequal_20_3e',['hashtable&lt; mystl::pair&lt; const Key, T &gt;, Hash, KeyEqual &gt;',['../classmystl_1_1hashtable.html',1,'mystl']]],
  ['hashtable_3c_20pair_3c_20const_20key_2c_20t_20_3e_2c_20hash_2c_20keyequal_20_3e',['hashtable&lt; pair&lt; const Key, T &gt;, Hash, KeyEqual &gt;',['../classmystl_1_1hashtable.html',1,'mystl']]],
  ['hashtable_5fnode',['hashtable_node',['../structmystl_1_1hashtable__node.html',1,'mystl']]],
  ['hasrequiredadinfo',['HasRequiredADInfo',['../structDifferentiation_1_1AD_1_1internal_1_1HasRequiredADInfo.html',1,'Differentiation::AD::internal']]],
  ['hdf5object',['HDF5Object',['../classHDF5_1_1HDF5Object.html',1,'HDF5']]],
  ['heightdirectiondata',['HeightDirectionData',['../structNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1HeightDirectionData.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['helper',['Helper',['../structColorEnriched_1_1Helper.html',1,'ColorEnriched']]],
  ['helperbase',['HelperBase',['../classDifferentiation_1_1AD_1_1HelperBase.html',1,'Differentiation::AD']]],
  ['hermiteinterpolation',['HermiteInterpolation',['../classPolynomials_1_1HermiteInterpolation.html',1,'Polynomials']]],
  ['hermitelikeinterpolation',['HermiteLikeInterpolation',['../classPolynomials_1_1HermiteLikeInterpolation.html',1,'Polynomials']]],
  ['hessiantype',['HessianType',['../structDifferentiation_1_1AD_1_1internal_1_1HessianType.html',1,'Differentiation::AD::internal']]],
  ['hessiantype_3c_20fevaluesextractors_3a_3ascalar_2c_20fevaluesextractors_3a_3asymmetrictensor_3c_202_20_3e_20_3e',['HessianType&lt; FEValuesExtractors::Scalar, FEValuesExtractors::SymmetricTensor&lt; 2 &gt; &gt;',['../structDifferentiation_1_1AD_1_1internal_1_1HessianType_3_01FEValuesExtractors_1_1Scalar_00_01FEV29da66e3a12fe81bc637f7a53e31d995.html',1,'Differentiation::AD::internal']]],
  ['hessiantype_3c_20fevaluesextractors_3a_3asymmetrictensor_3c_202_20_3e_2c_20fevaluesextractors_3a_3ascalar_20_3e',['HessianType&lt; FEValuesExtractors::SymmetricTensor&lt; 2 &gt;, FEValuesExtractors::Scalar &gt;',['../structDifferentiation_1_1AD_1_1internal_1_1HessianType_3_01FEValuesExtractors_1_1SymmetricTensor1fcc01f5160dd02c8dce75aa519a71c5.html',1,'Differentiation::AD::internal']]],
  ['hessiantype_3c_20fevaluesextractors_3a_3asymmetrictensor_3c_202_20_3e_2c_20fevaluesextractors_3a_3asymmetrictensor_3c_202_20_3e_20_3e',['HessianType&lt; FEValuesExtractors::SymmetricTensor&lt; 2 &gt;, FEValuesExtractors::SymmetricTensor&lt; 2 &gt; &gt;',['../structDifferentiation_1_1AD_1_1internal_1_1HessianType_3_01FEValuesExtractors_1_1SymmetricTensor53e75a7bea61297f7f3bd95fe09ad3ea.html',1,'Differentiation::AD::internal']]],
  ['hierarchical',['Hierarchical',['../classPolynomials_1_1Hierarchical.html',1,'Polynomials']]],
  ['histogram',['Histogram',['../classHistogram.html',1,'']]],
  ['host',['Host',['../structMemorySpace_1_1Host.html',1,'MemorySpace']]],
  ['householder',['Householder',['../classHouseholder.html',1,'']]],
  ['householder_3c_20inverse_5ftype_20_3e',['Householder&lt; inverse_type &gt;',['../classHouseholder.html',1,'']]],
  ['householder_3c_20inversenumbertype_20_3e',['Householder&lt; InverseNumberType &gt;',['../classHouseholder.html',1,'']]],
  ['ht_5fconst_5fiterator',['ht_const_iterator',['../structmystl_1_1ht__const__iterator.html',1,'mystl']]],
  ['ht_5fconst_5flocal_5fiterator',['ht_const_local_iterator',['../structmystl_1_1ht__const__local__iterator.html',1,'mystl']]],
  ['ht_5fiterator',['ht_iterator',['../structmystl_1_1ht__iterator.html',1,'mystl']]],
  ['ht_5fiterator_5fbase',['ht_iterator_base',['../structmystl_1_1ht__iterator__base.html',1,'mystl']]],
  ['ht_5flocal_5fiterator',['ht_local_iterator',['../structmystl_1_1ht__local__iterator.html',1,'mystl']]],
  ['ht_5fvalue_5ftraits',['ht_value_traits',['../structmystl_1_1ht__value__traits.html',1,'mystl']]],
  ['ht_5fvalue_5ftraits_5fimp',['ht_value_traits_imp',['../structmystl_1_1ht__value__traits__imp.html',1,'mystl']]],
  ['ht_5fvalue_5ftraits_5fimp_3c_20t_2c_20true_20_3e',['ht_value_traits_imp&lt; T, true &gt;',['../structmystl_1_1ht__value__traits__imp_3_01T_00_01true_01_4.html',1,'mystl']]]
];
