var searchData=
[
  ['barycentricpolynomial',['BarycentricPolynomial',['../classBarycentricPolynomial.html',1,'']]],
  ['barycentricpolynomial_3c_20dim_20_3e',['BarycentricPolynomial&lt; dim &gt;',['../classBarycentricPolynomial.html',1,'']]],
  ['barycentricpolynomials',['BarycentricPolynomials',['../classBarycentricPolynomials.html',1,'']]],
  ['barycentricpolynomials_3c_201_20_3e',['BarycentricPolynomials&lt; 1 &gt;',['../classBarycentricPolynomials.html',1,'']]],
  ['barycentricpolynomials_3c_202_20_3e',['BarycentricPolynomials&lt; 2 &gt;',['../classBarycentricPolynomials.html',1,'']]],
  ['base',['Base',['../classRepartitioningPolicyTools_1_1Base.html',1,'RepartitioningPolicyTools::Base&lt; dim, spacedim &gt;'],['../classMatrixFreeOperators_1_1Base.html',1,'MatrixFreeOperators::Base&lt; dim, VectorType, VectorizedArrayType &gt;'],['../classinternal_1_1MatrixFreeFunctions_1_1VectorDataExchange_1_1Base.html',1,'internal::MatrixFreeFunctions::VectorDataExchange::Base'],['../classFEInterfaceViews_1_1Base.html',1,'FEInterfaceViews::Base&lt; dim, spacedim &gt;']]],
  ['baseiterator',['BaseIterator',['../classBaseIterator.html',1,'']]],
  ['baseqr',['BaseQR',['../classBaseQR.html',1,'']]],
  ['batchoptimizer',['BatchOptimizer',['../classDifferentiation_1_1SD_1_1BatchOptimizer.html',1,'Differentiation::SD']]],
  ['bessel1',['Bessel1',['../classFunctions_1_1Bessel1.html',1,'Functions']]],
  ['binop_5faddition',['Binop_Addition',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Addition.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5faddition_3c_20std_3a_3acomplex_3c_20number_20_3e_20_3e',['Binop_Addition&lt; std::complex&lt; Number &gt; &gt;',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Addition_3_01std_1_1complex_3_01Number_01_4_01_4.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fmax',['Binop_Max',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Max.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fmax_3c_20std_3a_3acomplex_3c_20number_20_3e_20_3e',['Binop_Max&lt; std::complex&lt; Number &gt; &gt;',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Max_3_01std_1_1complex_3_01Number_01_4_01_4.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fmin',['Binop_Min',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Min.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fmin_3c_20std_3a_3acomplex_3c_20number_20_3e_20_3e',['Binop_Min&lt; std::complex&lt; Number &gt; &gt;',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Min_3_01std_1_1complex_3_01Number_01_4_01_4.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fsubtraction',['Binop_Subtraction',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Subtraction.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['binop_5fsubtraction_3c_20std_3a_3acomplex_3c_20number_20_3e_20_3e',['Binop_Subtraction&lt; std::complex&lt; Number &gt; &gt;',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1Binop__Subtraction_3_01std_1_1complex_3_01Number_01_4_01_4.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['blockdynamicsparsitypattern',['BlockDynamicSparsityPattern',['../classBlockDynamicSparsityPattern.html',1,'']]],
  ['blockindices',['BlockIndices',['../classBlockIndices.html',1,'']]],
  ['blockinfo',['BlockInfo',['../classBlockInfo.html',1,'']]],
  ['blocklinearoperator',['BlockLinearOperator',['../classBlockLinearOperator.html',1,'']]],
  ['blockmask',['BlockMask',['../classBlockMask.html',1,'']]],
  ['blockmatrixbase',['BlockMatrixBase',['../classBlockMatrixBase.html',1,'']]],
  ['blockmatrixbase_3c_20sparsematrix_20_3e',['BlockMatrixBase&lt; SparseMatrix &gt;',['../classBlockMatrixBase.html',1,'']]],
  ['blockmatrixbase_3c_20sparsematrix_3c_20number_20_3e_20_3e',['BlockMatrixBase&lt; SparseMatrix&lt; number &gt; &gt;',['../classBlockMatrixBase.html',1,'']]],
  ['blocksparsematrix',['BlockSparseMatrix',['../classBlockSparseMatrix.html',1,'BlockSparseMatrix&lt; number &gt;'],['../classPETScWrappers_1_1MPI_1_1BlockSparseMatrix.html',1,'PETScWrappers::MPI::BlockSparseMatrix'],['../classTrilinosWrappers_1_1BlockSparseMatrix.html',1,'TrilinosWrappers::BlockSparseMatrix']]],
  ['blocksparsematrixez',['BlockSparseMatrixEZ',['../classBlockSparseMatrixEZ.html',1,'']]],
  ['blocksparsitypattern',['BlockSparsityPattern',['../classTrilinosWrappers_1_1BlockSparsityPattern.html',1,'TrilinosWrappers::BlockSparsityPattern'],['../classBlockSparsityPattern.html',1,'BlockSparsityPattern']]],
  ['blocksparsitypatternbase',['BlockSparsityPatternBase',['../classBlockSparsityPatternBase.html',1,'']]],
  ['blocksparsitypatternbase_3c_20dynamicsparsitypattern_20_3e',['BlockSparsityPatternBase&lt; DynamicSparsityPattern &gt;',['../classBlockSparsityPatternBase.html',1,'']]],
  ['blocksparsitypatternbase_3c_20sparsitypattern_20_3e',['BlockSparsityPatternBase&lt; SparsityPattern &gt;',['../classBlockSparsityPatternBase.html',1,'']]],
  ['blockvector',['BlockVector',['../classBlockVector.html',1,'BlockVector&lt; Number &gt;'],['../classLinearAlgebra_1_1distributed_1_1BlockVector.html',1,'LinearAlgebra::distributed::BlockVector&lt; Number &gt;'],['../classPETScWrappers_1_1MPI_1_1BlockVector.html',1,'PETScWrappers::MPI::BlockVector'],['../classTrilinosWrappers_1_1MPI_1_1BlockVector.html',1,'TrilinosWrappers::MPI::BlockVector']]],
  ['blockvector_3c_20number_20_3e',['BlockVector&lt; number &gt;',['../classBlockVector.html',1,'']]],
  ['blockvectorbase',['BlockVectorBase',['../classBlockVectorBase.html',1,'']]],
  ['blockvectorbase_3c_20mpi_3a_3avector_20_3e',['BlockVectorBase&lt; MPI::Vector &gt;',['../classBlockVectorBase.html',1,'']]],
  ['blockvectorbase_3c_20vector_20_3e',['BlockVectorBase&lt; Vector &gt;',['../classBlockVectorBase.html',1,'']]],
  ['blockvectorbase_3c_20vector_3c_20number_20_3e_20_3e',['BlockVectorBase&lt; Vector&lt; number &gt; &gt;',['../classBlockVectorBase.html',1,'BlockVectorBase&lt; Vector&lt; number &gt; &gt;'],['../classBlockVectorBase.html',1,'BlockVectorBase&lt; Vector&lt; Number &gt; &gt;']]],
  ['body',['Body',['../structparallel_1_1internal_1_1Body.html',1,'parallel::internal']]],
  ['bool',['Bool',['../classPatterns_1_1Bool.html',1,'Patterns']]],
  ['boolstorage',['BoolStorage',['../structinternal_1_1TemplateConstraints_1_1BoolStorage.html',1,'internal::TemplateConstraints']]],
  ['boundaryormaterialid',['BoundaryOrMaterialId',['../structinternal_1_1TriangulationImplementation_1_1TriaObjects_1_1BoundaryOrMaterialId.html',1,'internal::TriangulationImplementation::TriaObjects']]],
  ['boundingbox',['BoundingBox',['../classBoundingBox.html',1,'']]],
  ['boundingbox_3c_200_2c_20number_20_3e',['BoundingBox&lt; 0, Number &gt;',['../classBoundingBox_3_010_00_01Number_01_4.html',1,'']]],
  ['boundingbox_3c_203_2c_20float_20_3e',['BoundingBox&lt; 3, float &gt;',['../classBoundingBox.html',1,'']]],
  ['boundingbox_3c_20boost_3a_3ageometry_3a_3adimension_3c_20box_20_3e_3a_3avalue_20_3e',['BoundingBox&lt; boost::geometry::dimension&lt; Box &gt;::value &gt;',['../classBoundingBox.html',1,'']]],
  ['boundingboxdataout',['BoundingBoxDataOut',['../classBoundingBoxDataOut.html',1,'']]],
  ['boundingboxintersectpredicate',['BoundingBoxIntersectPredicate',['../classArborXWrappers_1_1BoundingBoxIntersectPredicate.html',1,'ArborXWrappers']]],
  ['boundingboxnearestpredicate',['BoundingBoxNearestPredicate',['../classArborXWrappers_1_1BoundingBoxNearestPredicate.html',1,'ArborXWrappers']]],
  ['boundingboxpredicate',['BoundingBoxPredicate',['../classArborXWrappers_1_1BoundingBoxPredicate.html',1,'ArborXWrappers']]],
  ['bvh',['BVH',['../classArborXWrappers_1_1BVH.html',1,'ArborXWrappers']]]
];
