var searchData=
[
  ['range',['Range',['../structIndexSet_1_1Range.html',1,'IndexSet']]],
  ['rankinfo',['RankInfo',['../structPatterns_1_1Tools_1_1internal_1_1RankInfo.html',1,'Patterns::Tools::internal']]],
  ['rankinfo_3c_20componentmask_20_3e',['RankInfo&lt; ComponentMask &gt;',['../structPatterns_1_1Tools_1_1internal_1_1RankInfo_3_01ComponentMask_01_4.html',1,'Patterns::Tools::internal']]],
  ['rankinfo_3c_20point_3c_20dim_2c_20number_20_3e_20_3e',['RankInfo&lt; Point&lt; dim, Number &gt; &gt;',['../structPatterns_1_1Tools_1_1internal_1_1RankInfo_3_01Point_3_01dim_00_01Number_01_4_01_4.html',1,'Patterns::Tools::internal']]],
  ['rankinfo_3c_20std_3a_3acomplex_3c_20number_20_3e_20_3e',['RankInfo&lt; std::complex&lt; Number &gt; &gt;',['../structPatterns_1_1Tools_1_1internal_1_1RankInfo_3_01std_1_1complex_3_01Number_01_4_01_4.html',1,'Patterns::Tools::internal']]],
  ['rankinfo_3c_20std_3a_3apair_3c_20key_2c_20value_20_3e_20_3e',['RankInfo&lt; std::pair&lt; Key, Value &gt; &gt;',['../structPatterns_1_1Tools_1_1internal_1_1RankInfo_3_01std_1_1pair_3_01Key_00_01Value_01_4_01_4.html',1,'Patterns::Tools::internal']]],
  ['rankinfo_3c_20std_3a_3atuple_3c_20types_2e_2e_2e_20_3e_20_3e',['RankInfo&lt; std::tuple&lt; Types... &gt; &gt;',['../structPatterns_1_1Tools_1_1internal_1_1RankInfo_3_01std_1_1tuple_3_01Types_8_8_8_01_4_01_4.html',1,'Patterns::Tools::internal']]],
  ['rankinfo_3c_20std_3a_3aunique_5fptr_3c_20functionparser_3c_20dim_20_3e_20_3e_20_3e',['RankInfo&lt; std::unique_ptr&lt; FunctionParser&lt; dim &gt; &gt; &gt;',['../structPatterns_1_1Tools_1_1internal_1_1RankInfo_3_01std_1_1unique__ptr_3_01FunctionParser_3_01dim_01_4_01_4_01_4.html',1,'Patterns::Tools::internal']]],
  ['rankinfo_3c_20t_2c_20typename_20std_3a_3aenable_5fif_3c_20is_5flist_5fcompatible_3c_20t_20_3e_3a_3avalue_20_3e_3a_3atype_20_3e',['RankInfo&lt; T, typename std::enable_if&lt; is_list_compatible&lt; T &gt;::value &gt;::type &gt;',['../structPatterns_1_1Tools_1_1internal_1_1RankInfo_3_01T_00_01typename_01std_1_1enable__if_3_01is__c88ec1062ff9492d04b67e980cc95e9c.html',1,'Patterns::Tools::internal']]],
  ['rankinfo_3c_20t_2c_20typename_20std_3a_3aenable_5fif_3c_20is_5fmap_5fcompatible_3c_20t_20_3e_3a_3avalue_20_3e_3a_3atype_20_3e',['RankInfo&lt; T, typename std::enable_if&lt; is_map_compatible&lt; T &gt;::value &gt;::type &gt;',['../structPatterns_1_1Tools_1_1internal_1_1RankInfo_3_01T_00_01typename_01std_1_1enable__if_3_01is__02be699ea50c9e39d8e768fad16909d5.html',1,'Patterns::Tools::internal']]],
  ['rankinfo_3c_20tensor_3c_201_2c_20dim_2c_20number_20_3e_20_3e',['RankInfo&lt; Tensor&lt; 1, dim, Number &gt; &gt;',['../structPatterns_1_1Tools_1_1internal_1_1RankInfo.html',1,'Patterns::Tools::internal']]],
  ['rankinfo_3c_20tensor_3c_20rank_2c_20dim_2c_20number_20_3e_20_3e',['RankInfo&lt; Tensor&lt; rank, dim, Number &gt; &gt;',['../structPatterns_1_1Tools_1_1internal_1_1RankInfo_3_01Tensor_3_01rank_00_01dim_00_01Number_01_4_01_4.html',1,'Patterns::Tools::internal']]],
  ['readwritevector',['ReadWriteVector',['../classLinearAlgebra_1_1ReadWriteVector.html',1,'LinearAlgebra']]],
  ['reductioncontrol',['ReductionControl',['../classReductionControl.html',1,'']]],
  ['reductiononsubranges',['ReductionOnSubranges',['../structparallel_1_1internal_1_1ReductionOnSubranges.html',1,'parallel::internal']]],
  ['reference',['Reference',['../classChunkSparseMatrixIterators_1_1Accessor_3_01number_00_01false_01_4_1_1Reference.html',1,'ChunkSparseMatrixIterators::Accessor&lt; number, false &gt;::Reference'],['../classSparseMatrixIterators_1_1Accessor_3_01number_00_01false_01_4_1_1Reference.html',1,'SparseMatrixIterators::Accessor&lt; number, false &gt;::Reference'],['../classTrilinosWrappers_1_1SparseMatrixIterators_1_1Accessor_3_01false_01_4_1_1Reference.html',1,'TrilinosWrappers::SparseMatrixIterators::Accessor&lt; false &gt;::Reference']]],
  ['referencecell',['ReferenceCell',['../classReferenceCell.html',1,'']]],
  ['referencetype',['ReferenceType',['../structTensorAccessors_1_1internal_1_1ReferenceType.html',1,'TensorAccessors::internal']]],
  ['referencetype_3c_20reorderedindexview_3c_20index_2c_20rank_2c_20t_20_3e_20_3e',['ReferenceType&lt; ReorderedIndexView&lt; index, rank, T &gt; &gt;',['../structTensorAccessors_1_1internal_1_1ReferenceType_3_01ReorderedIndexView_3_01index_00_01rank_00_01T_01_4_01_4.html',1,'TensorAccessors::internal']]],
  ['referencetype_3c_20storeindex_3c_20rank_2c_20s_20_3e_20_3e',['ReferenceType&lt; StoreIndex&lt; rank, S &gt; &gt;',['../structTensorAccessors_1_1internal_1_1ReferenceType_3_01StoreIndex_3_01rank_00_01S_01_4_01_4.html',1,'TensorAccessors::internal']]],
  ['refinementcase',['RefinementCase',['../classRefinementCase.html',1,'']]],
  ['refinementdata',['RefinementData',['../structTimeStepBase__Tria__Flags_1_1RefinementData.html',1,'TimeStepBase_Tria_Flags']]],
  ['refinementflags',['RefinementFlags',['../structTimeStepBase__Tria__Flags_1_1RefinementFlags.html',1,'TimeStepBase_Tria_Flags']]],
  ['refinementpossibilities',['RefinementPossibilities',['../structRefinementPossibilities.html',1,'']]],
  ['refinementpossibilities_3c_201_20_3e',['RefinementPossibilities&lt; 1 &gt;',['../structRefinementPossibilities_3_011_01_4.html',1,'']]],
  ['refinementpossibilities_3c_202_20_3e',['RefinementPossibilities&lt; 2 &gt;',['../structRefinementPossibilities_3_012_01_4.html',1,'']]],
  ['refinementpossibilities_3c_203_20_3e',['RefinementPossibilities&lt; 3 &gt;',['../structRefinementPossibilities_3_013_01_4.html',1,'']]],
  ['reinithelper',['ReinitHelper',['../classinternal_1_1LinearOperatorImplementation_1_1ReinitHelper.html',1,'internal::LinearOperatorImplementation']]],
  ['reinithelper_3c_20blockvector_3c_20number_20_3e_20_3e',['ReinitHelper&lt; BlockVector&lt; number &gt; &gt;',['../classinternal_1_1LinearOperatorImplementation_1_1ReinitHelper_3_01BlockVector_3_01number_01_4_01_4.html',1,'internal::LinearOperatorImplementation']]],
  ['reinithelper_3c_20linearalgebra_3a_3adistributed_3a_3avector_3c_20number_20_3e_20_3e',['ReinitHelper&lt; LinearAlgebra::distributed::Vector&lt; Number &gt; &gt;',['../classinternal_1_1LinearOperatorImplementation_1_1ReinitHelper_3_01LinearAlgebra_1_1distributed_1_1Vector_3_01Number_01_4_01_4.html',1,'internal::LinearOperatorImplementation']]],
  ['reinithelper_3c_20petscwrappers_3a_3ampi_3a_3ablockvector_20_3e',['ReinitHelper&lt; PETScWrappers::MPI::BlockVector &gt;',['../classinternal_1_1LinearOperatorImplementation_1_1ReinitHelper_3_01PETScWrappers_1_1MPI_1_1BlockVector_01_4.html',1,'internal::LinearOperatorImplementation']]],
  ['reinithelper_3c_20petscwrappers_3a_3ampi_3a_3avector_20_3e',['ReinitHelper&lt; PETScWrappers::MPI::Vector &gt;',['../classinternal_1_1LinearOperatorImplementation_1_1ReinitHelper_3_01PETScWrappers_1_1MPI_1_1Vector_01_4.html',1,'internal::LinearOperatorImplementation']]],
  ['reinithelper_3c_20trilinoswrappers_3a_3ampi_3a_3ablockvector_20_3e',['ReinitHelper&lt; TrilinosWrappers::MPI::BlockVector &gt;',['../classinternal_1_1LinearOperatorImplementation_1_1ReinitHelper_3_01TrilinosWrappers_1_1MPI_1_1BlockVector_01_4.html',1,'internal::LinearOperatorImplementation']]],
  ['reinithelper_3c_20trilinoswrappers_3a_3ampi_3a_3avector_20_3e',['ReinitHelper&lt; TrilinosWrappers::MPI::Vector &gt;',['../classinternal_1_1LinearOperatorImplementation_1_1ReinitHelper_3_01TrilinosWrappers_1_1MPI_1_1Vector_01_4.html',1,'internal::LinearOperatorImplementation']]],
  ['relaxationblock',['RelaxationBlock',['../classRelaxationBlock.html',1,'']]],
  ['relaxationblockjacobi',['RelaxationBlockJacobi',['../classRelaxationBlockJacobi.html',1,'']]],
  ['relaxationblocksor',['RelaxationBlockSOR',['../classRelaxationBlockSOR.html',1,'']]],
  ['relaxationblockssor',['RelaxationBlockSSOR',['../classRelaxationBlockSSOR.html',1,'']]],
  ['remotepointevaluation',['RemotePointEvaluation',['../classUtilities_1_1MPI_1_1RemotePointEvaluation.html',1,'Utilities::MPI']]],
  ['removecomplexwrapper',['RemoveComplexWrapper',['../structDifferentiation_1_1AD_1_1internal_1_1RemoveComplexWrapper.html',1,'Differentiation::AD::internal']]],
  ['reorderedindexview',['ReorderedIndexView',['../classTensorAccessors_1_1internal_1_1ReorderedIndexView.html',1,'TensorAccessors::internal']]],
  ['reorderedindexview_3c_200_2c_201_2c_20t_20_3e',['ReorderedIndexView&lt; 0, 1, T &gt;',['../classTensorAccessors_1_1internal_1_1ReorderedIndexView_3_010_00_011_00_01T_01_4.html',1,'TensorAccessors::internal']]],
  ['reorderedindexview_3c_200_2c_20rank_2c_20t_20_3e',['ReorderedIndexView&lt; 0, rank, T &gt;',['../classTensorAccessors_1_1internal_1_1ReorderedIndexView_3_010_00_01rank_00_01T_01_4.html',1,'TensorAccessors::internal']]],
  ['residuallinearization',['ResidualLinearization',['../classDifferentiation_1_1AD_1_1ResidualLinearization.html',1,'Differentiation::AD']]],
  ['residuallocalblockstoglobalblocks',['ResidualLocalBlocksToGlobalBlocks',['../classMeshWorker_1_1Assembler_1_1ResidualLocalBlocksToGlobalBlocks.html',1,'MeshWorker::Assembler']]],
  ['residualsimple',['ResidualSimple',['../classMeshWorker_1_1Assembler_1_1ResidualSimple.html',1,'MeshWorker::Assembler']]],
  ['return_5fvalue',['return_value',['../structThreads_1_1internal_1_1return__value.html',1,'Threads::internal']]],
  ['return_5fvalue_3c_20rt_20_26_20_3e',['return_value&lt; RT &amp; &gt;',['../structThreads_1_1internal_1_1return__value_3_01RT_01_6_01_4.html',1,'Threads::internal']]],
  ['return_5fvalue_3c_20void_20_3e',['return_value&lt; void &gt;',['../structThreads_1_1internal_1_1return__value_3_01void_01_4.html',1,'Threads::internal']]],
  ['returntype',['ReturnType',['../structTensorAccessors_1_1ReturnType.html',1,'TensorAccessors']]],
  ['returntype_3c_200_2c_20t_20_3e',['ReturnType&lt; 0, T &gt;',['../structTensorAccessors_1_1ReturnType_3_010_00_01T_01_4.html',1,'TensorAccessors']]],
  ['rgbvalues',['RgbValues',['../structDataOutBase_1_1EpsFlags_1_1RgbValues.html',1,'DataOutBase::EpsFlags']]],
  ['rotate3d',['Rotate3d',['../classGridTools_1_1internal_1_1Rotate3d.html',1,'GridTools::internal']]],
  ['rowinfo',['RowInfo',['../structSparseMatrixEZ_1_1RowInfo.html',1,'SparseMatrixEZ']]],
  ['rungekutta',['RungeKutta',['../classTimeStepping_1_1RungeKutta.html',1,'TimeStepping']]]
];
