var searchData=
[
  ['q1wedgefunction',['Q1WedgeFunction',['../classFunctions_1_1Q1WedgeFunction.html',1,'Functions']]],
  ['qanisotropic',['QAnisotropic',['../classQAnisotropic.html',1,'']]],
  ['qcollection',['QCollection',['../classhp_1_1QCollection.html',1,'hp']]],
  ['qcollection_3c_20dim_20_2d_201_20_3e',['QCollection&lt; dim - 1 &gt;',['../classhp_1_1QCollection.html',1,'hp']]],
  ['qcollection_3c_20q_5fdim_20_3e',['QCollection&lt; q_dim &gt;',['../classhp_1_1QCollection.html',1,'hp']]],
  ['qcollection_3c_20structdim_20_3e',['QCollection&lt; structdim &gt;',['../classhp_1_1QCollection.html',1,'hp']]],
  ['qduffy',['QDuffy',['../classQDuffy.html',1,'']]],
  ['qgauss',['QGauss',['../classQGauss.html',1,'']]],
  ['qgausschebyshev',['QGaussChebyshev',['../classQGaussChebyshev.html',1,'']]],
  ['qgausslobatto',['QGaussLobatto',['../classQGaussLobatto.html',1,'']]],
  ['qgausslobatto_3c_201_20_3e',['QGaussLobatto&lt; 1 &gt;',['../classQGaussLobatto.html',1,'']]],
  ['qgausslobattochebyshev',['QGaussLobattoChebyshev',['../classQGaussLobattoChebyshev.html',1,'']]],
  ['qgausslog',['QGaussLog',['../classQGaussLog.html',1,'']]],
  ['qgausslogr',['QGaussLogR',['../classQGaussLogR.html',1,'']]],
  ['qgaussoneoverr',['QGaussOneOverR',['../classQGaussOneOverR.html',1,'']]],
  ['qgausspyramid',['QGaussPyramid',['../classQGaussPyramid.html',1,'']]],
  ['qgaussradauchebyshev',['QGaussRadauChebyshev',['../classQGaussRadauChebyshev.html',1,'']]],
  ['qgausssimplex',['QGaussSimplex',['../classQGaussSimplex.html',1,'']]],
  ['qgausswedge',['QGaussWedge',['../classQGaussWedge.html',1,'']]],
  ['qiterated',['QIterated',['../classQIterated.html',1,'']]],
  ['qmidpoint',['QMidpoint',['../classQMidpoint.html',1,'']]],
  ['qmilne',['QMilne',['../classQMilne.html',1,'']]],
  ['qprojector',['QProjector',['../classQProjector.html',1,'']]],
  ['qr',['QR',['../classQR.html',1,'']]],
  ['qsimplex',['QSimplex',['../classQSimplex.html',1,'']]],
  ['qsimplex_3c_202_20_3e',['QSimplex&lt; 2 &gt;',['../classQSimplex.html',1,'']]],
  ['qsimpson',['QSimpson',['../classQSimpson.html',1,'']]],
  ['qsorted',['QSorted',['../classQSorted.html',1,'']]],
  ['qsplit',['QSplit',['../classQSplit.html',1,'']]],
  ['qtelles',['QTelles',['../classQTelles.html',1,'']]],
  ['qtrapezoid',['QTrapezoid',['../classQTrapezoid.html',1,'']]],
  ['qtrianglepolar',['QTrianglePolar',['../classQTrianglePolar.html',1,'']]],
  ['quadrature',['Quadrature',['../classQuadrature.html',1,'']]],
  ['quadrature_3c_201_20_3e',['Quadrature&lt; 1 &gt;',['../classQuadrature.html',1,'']]],
  ['quadrature_3c_20dim_20_2d_201_20_3e',['Quadrature&lt; dim - 1 &gt;',['../classQuadrature.html',1,'']]],
  ['quadrature_3c_20structdim_20_3e',['Quadrature&lt; structdim &gt;',['../classQuadrature.html',1,'']]],
  ['quadraturedescriptor',['QuadratureDescriptor',['../structinternal_1_1MatrixFreeFunctions_1_1MappingInfoStorage_1_1QuadratureDescriptor.html',1,'internal::MatrixFreeFunctions::MappingInfoStorage']]],
  ['quadratureselector',['QuadratureSelector',['../classQuadratureSelector.html',1,'']]],
  ['qweddle',['QWeddle',['../classQWeddle.html',1,'']]],
  ['qwitherdenvincentsimplex',['QWitherdenVincentSimplex',['../classQWitherdenVincentSimplex.html',1,'']]]
];
