var searchData=
[
  ['valuetype',['ValueType',['../structTensorAccessors_1_1ValueType.html',1,'TensorAccessors']]],
  ['valuetype_3c_20const_20t_20_3e',['ValueType&lt; const T &gt;',['../structTensorAccessors_1_1ValueType_3_01const_01T_01_4.html',1,'TensorAccessors']]],
  ['valuetype_3c_20const_20t_5bn_5d_3e',['ValueType&lt; const T[N]&gt;',['../structTensorAccessors_1_1ValueType_3_01const_01T[N]_4.html',1,'TensorAccessors']]],
  ['valuetype_3c_20t_5bn_5d_3e',['ValueType&lt; T[N]&gt;',['../structTensorAccessors_1_1ValueType_3_01T[N]_4.html',1,'TensorAccessors']]],
  ['vector',['Vector',['../classVector.html',1,'Vector&lt; Number &gt;'],['../classTrilinosWrappers_1_1MPI_1_1Vector.html',1,'TrilinosWrappers::MPI::Vector'],['../classFEInterfaceViews_1_1Vector.html',1,'FEInterfaceViews::Vector&lt; dim, spacedim &gt;'],['../classLinearAlgebra_1_1distributed_1_1Vector.html',1,'LinearAlgebra::distributed::Vector&lt; Number, MemorySpace &gt;'],['../classFEValuesViews_1_1Vector.html',1,'FEValuesViews::Vector&lt; dim, spacedim &gt;'],['../classLinearAlgebra_1_1CUDAWrappers_1_1Vector.html',1,'LinearAlgebra::CUDAWrappers::Vector&lt; Number &gt;'],['../classLinearAlgebra_1_1TpetraWrappers_1_1Vector.html',1,'LinearAlgebra::TpetraWrappers::Vector&lt; Number &gt;'],['../structFEValuesExtractors_1_1Vector.html',1,'FEValuesExtractors::Vector'],['../structDataPostprocessorInputs_1_1Vector.html',1,'DataPostprocessorInputs::Vector&lt; spacedim &gt;'],['../classLinearAlgebra_1_1EpetraWrappers_1_1Vector.html',1,'LinearAlgebra::EpetraWrappers::Vector'],['../classLinearAlgebra_1_1Vector.html',1,'LinearAlgebra::Vector&lt; Number &gt;'],['../classPETScWrappers_1_1MPI_1_1Vector.html',1,'PETScWrappers::MPI::Vector']]],
  ['vector_3c_20double_20_3e',['Vector&lt; double &gt;',['../structDataPostprocessorInputs_1_1Vector.html',1,'DataPostprocessorInputs::Vector&lt; double &gt;'],['../classLinearAlgebra_1_1distributed_1_1Vector.html',1,'LinearAlgebra::distributed::Vector&lt; double &gt;']]],
  ['vector_3c_20number_20_3e',['Vector&lt; number &gt;',['../classVector.html',1,'Vector&lt; number &gt;'],['../classLinearAlgebra_1_1distributed_1_1Vector.html',1,'LinearAlgebra::distributed::Vector&lt; Number &gt;']]],
  ['vector_3c_20rangenumbertype_20_3e',['Vector&lt; RangeNumberType &gt;',['../classVector.html',1,'']]],
  ['vector_3c_20typename_20vectortype_3a_3avalue_5ftype_20_3e',['Vector&lt; typename VectorType::value_type &gt;',['../classVector.html',1,'']]],
  ['vector_5fcopy',['Vector_copy',['../structinternal_1_1VectorOperations_1_1Vector__copy.html',1,'internal::VectorOperations']]],
  ['vector_5fset',['Vector_set',['../structinternal_1_1VectorOperations_1_1Vector__set.html',1,'internal::VectorOperations']]],
  ['vectoradaptor',['VectorAdaptor',['../classRol_1_1VectorAdaptor.html',1,'Rol']]],
  ['vectorbase',['VectorBase',['../classPETScWrappers_1_1VectorBase.html',1,'PETScWrappers']]],
  ['vectordata',['VectorData',['../classMeshWorker_1_1VectorData.html',1,'MeshWorker']]],
  ['vectordatabase',['VectorDataBase',['../classMeshWorker_1_1VectorDataBase.html',1,'MeshWorker']]],
  ['vectordatabase_3c_20dim_2c_20spacedim_2c_20vectortype_3a_3avalue_5ftype_20_3e',['VectorDataBase&lt; dim, spacedim, VectorType::value_type &gt;',['../classMeshWorker_1_1VectorDataBase.html',1,'MeshWorker']]],
  ['vectordistributorlocaltoglobal',['VectorDistributorLocalToGlobal',['../structinternal_1_1VectorDistributorLocalToGlobal.html',1,'internal']]],
  ['vectorfunction',['VectorFunction',['../classDifferentiation_1_1AD_1_1VectorFunction.html',1,'Differentiation::AD']]],
  ['vectorfunctionfromscalarfunctionobject',['VectorFunctionFromScalarFunctionObject',['../classVectorFunctionFromScalarFunctionObject.html',1,'']]],
  ['vectorfunctionfromtensorfunction',['VectorFunctionFromTensorFunction',['../classVectorFunctionFromTensorFunction.html',1,'']]],
  ['vectorization_5fadd_5fav',['Vectorization_add_av',['../structinternal_1_1VectorOperations_1_1Vectorization__add__av.html',1,'internal::VectorOperations']]],
  ['vectorization_5fadd_5favpbw',['Vectorization_add_avpbw',['../structinternal_1_1VectorOperations_1_1Vectorization__add__avpbw.html',1,'internal::VectorOperations']]],
  ['vectorization_5fadd_5ffactor',['Vectorization_add_factor',['../structinternal_1_1VectorOperations_1_1Vectorization__add__factor.html',1,'internal::VectorOperations']]],
  ['vectorization_5fadd_5fv',['Vectorization_add_v',['../structinternal_1_1VectorOperations_1_1Vectorization__add__v.html',1,'internal::VectorOperations']]],
  ['vectorization_5fequ_5fau',['Vectorization_equ_au',['../structinternal_1_1VectorOperations_1_1Vectorization__equ__au.html',1,'internal::VectorOperations']]],
  ['vectorization_5fequ_5faubv',['Vectorization_equ_aubv',['../structinternal_1_1VectorOperations_1_1Vectorization__equ__aubv.html',1,'internal::VectorOperations']]],
  ['vectorization_5fequ_5faubvcw',['Vectorization_equ_aubvcw',['../structinternal_1_1VectorOperations_1_1Vectorization__equ__aubvcw.html',1,'internal::VectorOperations']]],
  ['vectorization_5fmultiply_5ffactor',['Vectorization_multiply_factor',['../structinternal_1_1VectorOperations_1_1Vectorization__multiply__factor.html',1,'internal::VectorOperations']]],
  ['vectorization_5fratio',['Vectorization_ratio',['../structinternal_1_1VectorOperations_1_1Vectorization__ratio.html',1,'internal::VectorOperations']]],
  ['vectorization_5fsadd_5fxav',['Vectorization_sadd_xav',['../structinternal_1_1VectorOperations_1_1Vectorization__sadd__xav.html',1,'internal::VectorOperations']]],
  ['vectorization_5fsadd_5fxavbw',['Vectorization_sadd_xavbw',['../structinternal_1_1VectorOperations_1_1Vectorization__sadd__xavbw.html',1,'internal::VectorOperations']]],
  ['vectorization_5fsadd_5fxv',['Vectorization_sadd_xv',['../structinternal_1_1VectorOperations_1_1Vectorization__sadd__xv.html',1,'internal::VectorOperations']]],
  ['vectorization_5fscale',['Vectorization_scale',['../structinternal_1_1VectorOperations_1_1Vectorization__scale.html',1,'internal::VectorOperations']]],
  ['vectorization_5fsubtract_5fv',['Vectorization_subtract_v',['../structinternal_1_1VectorOperations_1_1Vectorization__subtract__v.html',1,'internal::VectorOperations']]],
  ['vectorizedarray',['VectorizedArray',['../classVectorizedArray.html',1,'']]],
  ['vectorizedarray_3c_20double_20_3e',['VectorizedArray&lt; double &gt;',['../classVectorizedArray.html',1,'']]],
  ['vectorizedarray_3c_20number_20_3e',['VectorizedArray&lt; Number &gt;',['../classVectorizedArray.html',1,'']]],
  ['vectorizedarraybase',['VectorizedArrayBase',['../classVectorizedArrayBase.html',1,'']]],
  ['vectorizedarraybase_3c_20vectorizedarray_3c_20number_2c_20width_20_3e_2c_201_20_3e',['VectorizedArrayBase&lt; VectorizedArray&lt; Number, width &gt;, 1 &gt;',['../classVectorizedArrayBase.html',1,'']]],
  ['vectorizedarrayiterator',['VectorizedArrayIterator',['../classVectorizedArrayIterator.html',1,'']]],
  ['vectorizedarraywidthspecifier',['VectorizedArrayWidthSpecifier',['../structinternal_1_1VectorizedArrayWidthSpecifier.html',1,'internal']]],
  ['vectorizedarraywidthspecifier_3c_20double_20_3e',['VectorizedArrayWidthSpecifier&lt; double &gt;',['../structinternal_1_1VectorizedArrayWidthSpecifier_3_01double_01_4.html',1,'internal']]],
  ['vectorizedarraywidthspecifier_3c_20float_20_3e',['VectorizedArrayWidthSpecifier&lt; float &gt;',['../structinternal_1_1VectorizedArrayWidthSpecifier_3_01float_01_4.html',1,'internal']]],
  ['vectormemory',['VectorMemory',['../classVectorMemory.html',1,'']]],
  ['vectormemory_3c_20blockvector_3c_20number_20_3e_20_3e',['VectorMemory&lt; BlockVector&lt; number &gt; &gt;',['../classVectorMemory.html',1,'']]],
  ['vectormemory_3c_20vector_3c_20number_20_3e_20_3e',['VectorMemory&lt; Vector&lt; number &gt; &gt;',['../classVectorMemory.html',1,'']]],
  ['vectoroperation',['VectorOperation',['../structVectorOperation.html',1,'']]],
  ['vectorreader',['VectorReader',['../structinternal_1_1VectorReader.html',1,'internal']]],
  ['vectorselector',['VectorSelector',['../classMeshWorker_1_1VectorSelector.html',1,'MeshWorker']]],
  ['vectorsetter',['VectorSetter',['../structinternal_1_1VectorSetter.html',1,'internal']]],
  ['vectorspacevector',['VectorSpaceVector',['../classLinearAlgebra_1_1VectorSpaceVector.html',1,'LinearAlgebra']]],
  ['vectorspacevector_3c_20double_20_3e',['VectorSpaceVector&lt; double &gt;',['../classLinearAlgebra_1_1VectorSpaceVector.html',1,'LinearAlgebra']]],
  ['viewtype',['ViewType',['../structinternal_1_1FEValuesViews_1_1ViewType.html',1,'internal::FEValuesViews']]],
  ['viewtype_3c_20dim_2c_20spacedim_2c_20fevaluesextractors_3a_3ascalar_20_3e',['ViewType&lt; dim, spacedim, FEValuesExtractors::Scalar &gt;',['../structinternal_1_1FEValuesViews_1_1ViewType_3_01dim_00_01spacedim_00_01FEValuesExtractors_1_1Scalar_01_4.html',1,'internal::FEValuesViews']]],
  ['viewtype_3c_20dim_2c_20spacedim_2c_20fevaluesextractors_3a_3asymmetrictensor_3c_20rank_20_3e_20_3e',['ViewType&lt; dim, spacedim, FEValuesExtractors::SymmetricTensor&lt; rank &gt; &gt;',['../structinternal_1_1FEValuesViews_1_1ViewType_3_01dim_00_01spacedim_00_01FEValuesExtractors_1_1SymmetricTensor_3_01rank_01_4_01_4.html',1,'internal::FEValuesViews']]],
  ['viewtype_3c_20dim_2c_20spacedim_2c_20fevaluesextractors_3a_3atensor_3c_20rank_20_3e_20_3e',['ViewType&lt; dim, spacedim, FEValuesExtractors::Tensor&lt; rank &gt; &gt;',['../structinternal_1_1FEValuesViews_1_1ViewType_3_01dim_00_01spacedim_00_01FEValuesExtractors_1_1Tensor_3_01rank_01_4_01_4.html',1,'internal::FEValuesViews']]],
  ['viewtype_3c_20dim_2c_20spacedim_2c_20fevaluesextractors_3a_3avector_20_3e',['ViewType&lt; dim, spacedim, FEValuesExtractors::Vector &gt;',['../structinternal_1_1FEValuesViews_1_1ViewType_3_01dim_00_01spacedim_00_01FEValuesExtractors_1_1Vector_01_4.html',1,'internal::FEValuesViews']]],
  ['vtk',['Vtk',['../structGridOutFlags_1_1Vtk.html',1,'GridOutFlags']]],
  ['vtkflags',['VtkFlags',['../structDataOutBase_1_1VtkFlags.html',1,'DataOutBase']]],
  ['vtu',['Vtu',['../structGridOutFlags_1_1Vtu.html',1,'GridOutFlags']]]
];
