var searchData=
[
  ['data',['Data',['../structCUDAWrappers_1_1MatrixFree_1_1Data.html',1,'CUDAWrappers::MatrixFree']]],
  ['dataentrybase',['DataEntryBase',['../classinternal_1_1DataOutImplementation_1_1DataEntryBase.html',1,'internal::DataOutImplementation']]],
  ['datahost',['DataHost',['../structCUDAWrappers_1_1DataHost.html',1,'CUDAWrappers']]],
  ['dataout',['DataOut',['../classDataOut.html',1,'DataOut&lt; dim, spacedim &gt;'],['../classParticles_1_1DataOut.html',1,'Particles::DataOut&lt; dim, spacedim &gt;']]],
  ['dataout_3c_20dim_20_3e',['DataOut&lt; dim &gt;',['../classDataOut.html',1,'']]],
  ['dataout_5fdofdata',['DataOut_DoFData',['../classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dim_2c_20dim_20_2d_201_2c_20spacedim_2c_20spacedim_20_3e',['DataOut_DoFData&lt; dim, dim - 1, spacedim, spacedim &gt;',['../classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dim_2c_20dim_2b1_2c_20spacedim_2c_20spacedim_2b1_20_3e',['DataOut_DoFData&lt; dim, dim+1, spacedim, spacedim+1 &gt;',['../classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dim_2c_20dim_2c_20dim_2c_20dim_20_3e',['DataOut_DoFData&lt; dim, dim, dim, dim &gt;',['../classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dim_2c_20dim_2c_20spacedim_2c_20spacedim_20_3e',['DataOut_DoFData&lt; dim, dim, spacedim, spacedim &gt;',['../classDataOut__DoFData.html',1,'']]],
  ['dataoutfaces',['DataOutFaces',['../classDataOutFaces.html',1,'']]],
  ['dataoutfilter',['DataOutFilter',['../classDataOutBase_1_1DataOutFilter.html',1,'DataOutBase']]],
  ['dataoutfilterflags',['DataOutFilterFlags',['../structDataOutBase_1_1DataOutFilterFlags.html',1,'DataOutBase']]],
  ['dataoutinterface',['DataOutInterface',['../classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_200_2c_20spacedim_20_3e',['DataOutInterface&lt; 0, spacedim &gt;',['../classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_202_2c_202_20_3e',['DataOutInterface&lt; 2, 2 &gt;',['../classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_20dim_2b1_2c_20spacedim_2b1_20_3e',['DataOutInterface&lt; dim+1, spacedim+1 &gt;',['../classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_20dim_2c_20dim_20_3e',['DataOutInterface&lt; dim, dim &gt;',['../classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_20patch_5fdim_2c_20patch_5fspacedim_20_3e',['DataOutInterface&lt; patch_dim, patch_spacedim &gt;',['../classDataOutInterface.html',1,'']]],
  ['dataoutreader',['DataOutReader',['../classDataOutReader.html',1,'']]],
  ['dataoutrotation',['DataOutRotation',['../classDataOutRotation.html',1,'']]],
  ['dataoutstack',['DataOutStack',['../classDataOutStack.html',1,'']]],
  ['dataoutstack_3c_20dim_2c_20spacedim_2c_20void_20_3e',['DataOutStack&lt; dim, spacedim, void &gt;',['../classDataOutStack_3_01dim_00_01spacedim_00_01void_01_4.html',1,'']]],
  ['datapostprocessor',['DataPostprocessor',['../classDataPostprocessor.html',1,'']]],
  ['datapostprocessor_3c_20spacedim_20_3e',['DataPostprocessor&lt; spacedim &gt;',['../classDataPostprocessor.html',1,'']]],
  ['datapostprocessorscalar',['DataPostprocessorScalar',['../classDataPostprocessorScalar.html',1,'']]],
  ['datapostprocessortensor',['DataPostprocessorTensor',['../classDataPostprocessorTensor.html',1,'']]],
  ['datapostprocessorvector',['DataPostprocessorVector',['../classDataPostprocessorVector.html',1,'']]],
  ['datasetdescriptor',['DataSetDescriptor',['../classQProjector_1_1DataSetDescriptor.html',1,'QProjector']]],
  ['datatransfer',['DataTransfer',['../classparallel_1_1DistributedTriangulationBase_1_1DataTransfer.html',1,'parallel::DistributedTriangulationBase']]],
  ['datavector',['DataVector',['../structDataOutStack_3_01dim_00_01spacedim_00_01void_01_4_1_1DataVector.html',1,'DataOutStack&lt; dim, spacedim, void &gt;']]],
  ['deal_5fii_5fintermediateflags',['Deal_II_IntermediateFlags',['../structDataOutBase_1_1Deal__II__IntermediateFlags.html',1,'DataOutBase']]],
  ['defaulthierarchy',['DefaultHierarchy',['../structhp_1_1FECollection_1_1DefaultHierarchy.html',1,'hp::FECollection']]],
  ['defaultpolicy',['DefaultPolicy',['../classRepartitioningPolicyTools_1_1DefaultPolicy.html',1,'RepartitioningPolicyTools']]],
  ['derivativeform',['DerivativeForm',['../classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_201_2c_20dim_2c_20spacedim_20_3e',['DerivativeForm&lt; 1, dim, spacedim &gt;',['../classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_201_2c_20spacedim_2c_20dim_20_3e',['DerivativeForm&lt; 1, spacedim, dim &gt;',['../classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_202_2c_20dim_2c_20spacedim_20_3e',['DerivativeForm&lt; 2, dim, spacedim &gt;',['../classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_203_2c_20dim_2c_20spacedim_20_3e',['DerivativeForm&lt; 3, dim, spacedim &gt;',['../classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_204_2c_20dim_2c_20spacedim_20_3e',['DerivativeForm&lt; 4, dim, spacedim &gt;',['../classDerivativeForm.html',1,'']]],
  ['derivativeselector',['DerivativeSelector',['../classDerivativeApproximation_1_1internal_1_1DerivativeSelector.html',1,'DerivativeApproximation::internal']]],
  ['derivativeselector_3c_201_2c_20dim_20_3e',['DerivativeSelector&lt; 1, dim &gt;',['../classDerivativeApproximation_1_1internal_1_1DerivativeSelector_3_011_00_01dim_01_4.html',1,'DerivativeApproximation::internal']]],
  ['derivativeselector_3c_202_2c_20dim_20_3e',['DerivativeSelector&lt; 2, dim &gt;',['../classDerivativeApproximation_1_1internal_1_1DerivativeSelector_3_012_00_01dim_01_4.html',1,'DerivativeApproximation::internal']]],
  ['derivativeselector_3c_203_2c_20dim_20_3e',['DerivativeSelector&lt; 3, dim &gt;',['../classDerivativeApproximation_1_1internal_1_1DerivativeSelector_3_013_00_01dim_01_4.html',1,'DerivativeApproximation::internal']]],
  ['description',['Description',['../structTriangulationDescription_1_1Description.html',1,'TriangulationDescription']]],
  ['descriptiontemp',['DescriptionTemp',['../structTriangulationDescription_1_1Utilities_1_1DescriptionTemp.html',1,'TriangulationDescription::Utilities']]],
  ['dgp_5fdofs_5fper_5fcomponent',['DGP_dofs_per_component',['../structinternal_1_1MatrixFreeFunctions_1_1DGP__dofs__per__component.html',1,'internal::MatrixFreeFunctions']]],
  ['dgp_5fdofs_5fper_5fcomponent_3c_201_2c_20degree_20_3e',['DGP_dofs_per_component&lt; 1, degree &gt;',['../structinternal_1_1MatrixFreeFunctions_1_1DGP__dofs__per__component_3_011_00_01degree_01_4.html',1,'internal::MatrixFreeFunctions']]],
  ['diagonalmatrix',['DiagonalMatrix',['../classDiagonalMatrix.html',1,'']]],
  ['dictionary',['Dictionary',['../structUtilities_1_1MPI_1_1internal_1_1ComputeIndexOwner_1_1Dictionary.html',1,'Utilities::MPI::internal::ComputeIndexOwner']]],
  ['dictionaryoptimizer',['DictionaryOptimizer',['../structDifferentiation_1_1SD_1_1internal_1_1DictionaryOptimizer.html',1,'Differentiation::SD::internal']]],
  ['dictionarypayload',['DictionaryPayLoad',['../classUtilities_1_1MPI_1_1internal_1_1ComputeIndexOwner_1_1DictionaryPayLoad.html',1,'Utilities::MPI::internal::ComputeIndexOwner']]],
  ['dictionarysubstitutionvisitor',['DictionarySubstitutionVisitor',['../classDifferentiation_1_1SD_1_1internal_1_1DictionarySubstitutionVisitor.html',1,'Differentiation::SD::internal']]],
  ['dimension_3c_3a_3apoint_3c_20dim_2c_20number_20_3e_20_3e',['dimension&lt;::Point&lt; dim, Number &gt; &gt;',['../structboost_1_1geometry_1_1traits_1_1dimension_3_1_1Point_3_01dim_00_01Number_01_4_01_4.html',1,'boost::geometry::traits']]],
  ['directionalprojectionmanifold',['DirectionalProjectionManifold',['../classOpenCASCADE_1_1DirectionalProjectionManifold.html',1,'OpenCASCADE']]],
  ['directoryname',['DirectoryName',['../classPatterns_1_1DirectoryName.html',1,'Patterns']]],
  ['discretetime',['DiscreteTime',['../classDiscreteTime.html',1,'']]],
  ['distortedcelllist',['DistortedCellList',['../structTriangulation_1_1DistortedCellList.html',1,'Triangulation']]],
  ['distributedcomputepointlocationsinternal',['DistributedComputePointLocationsInternal',['../structGridTools_1_1internal_1_1DistributedComputePointLocationsInternal.html',1,'GridTools::internal']]],
  ['distributedtriangulationbase',['DistributedTriangulationBase',['../classparallel_1_1DistributedTriangulationBase.html',1,'parallel']]],
  ['distributedtriangulationbase_3c_201_2c_20spacedim_20_3e',['DistributedTriangulationBase&lt; 1, spacedim &gt;',['../classparallel_1_1DistributedTriangulationBase.html',1,'parallel']]],
  ['distributedtriangulationbase_3c_20dim_2c_20dim_20_3e',['DistributedTriangulationBase&lt; dim, dim &gt;',['../classparallel_1_1DistributedTriangulationBase.html',1,'parallel']]],
  ['dofaccessor',['DoFAccessor',['../classDoFAccessor.html',1,'']]],
  ['dofaccessor_3c_200_2c_201_2c_20spacedim_2c_20level_5fdof_5faccess_20_3e',['DoFAccessor&lt; 0, 1, spacedim, level_dof_access &gt;',['../classDoFAccessor_3_010_00_011_00_01spacedim_00_01level__dof__access_01_4.html',1,'']]],
  ['dofaccessor_3c_20dimension_5f_2c_20dimension_5f_2c_20space_5fdimension_5f_2c_20level_5fdof_5faccess_20_3e',['DoFAccessor&lt; dimension_, dimension_, space_dimension_, level_dof_access &gt;',['../classDoFAccessor.html',1,'']]],
  ['dofcellaccessor',['DoFCellAccessor',['../classDoFCellAccessor.html',1,'']]],
  ['doffaces',['DoFFaces',['../classinternal_1_1DoFHandlerImplementation_1_1DoFFaces.html',1,'internal::DoFHandlerImplementation']]],
  ['doffaces_3c_201_20_3e',['DoFFaces&lt; 1 &gt;',['../classinternal_1_1DoFHandlerImplementation_1_1DoFFaces_3_011_01_4.html',1,'internal::DoFHandlerImplementation']]],
  ['doffaces_3c_202_20_3e',['DoFFaces&lt; 2 &gt;',['../classinternal_1_1DoFHandlerImplementation_1_1DoFFaces_3_012_01_4.html',1,'internal::DoFHandlerImplementation']]],
  ['doffaces_3c_203_20_3e',['DoFFaces&lt; 3 &gt;',['../classinternal_1_1DoFHandlerImplementation_1_1DoFFaces_3_013_01_4.html',1,'internal::DoFHandlerImplementation']]],
  ['dofhandler',['DoFHandler',['../classDoFHandler.html',1,'']]],
  ['dofhandler_3c_201_2c_20spacedim_20_3e',['DoFHandler&lt; 1, spacedim &gt;',['../classDoFHandler.html',1,'']]],
  ['dofhandler_3c_20dim_20_3e',['DoFHandler&lt; dim &gt;',['../classDoFHandler.html',1,'']]],
  ['dofinfo',['DoFInfo',['../structinternal_1_1MatrixFreeFunctions_1_1DoFInfo.html',1,'internal::MatrixFreeFunctions::DoFInfo'],['../classMeshWorker_1_1DoFInfo.html',1,'MeshWorker::DoFInfo&lt; dim, spacedim, number &gt;']]],
  ['dofinfobox',['DoFInfoBox',['../classMeshWorker_1_1DoFInfoBox.html',1,'MeshWorker']]],
  ['dofinvalidaccessor',['DoFInvalidAccessor',['../classDoFInvalidAccessor.html',1,'']]],
  ['doflevel',['DoFLevel',['../classinternal_1_1DoFHandlerImplementation_1_1DoFLevel.html',1,'internal::DoFHandlerImplementation']]],
  ['dofobjects',['DoFObjects',['../classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'internal::DoFHandlerImplementation']]],
  ['dofobjects_3c_201_20_3e',['DoFObjects&lt; 1 &gt;',['../classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'internal::DoFHandlerImplementation']]],
  ['dofobjects_3c_202_20_3e',['DoFObjects&lt; 2 &gt;',['../classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'internal::DoFHandlerImplementation']]],
  ['dofoutputoperator',['DoFOutputOperator',['../classAlgorithms_1_1DoFOutputOperator.html',1,'Algorithms']]],
  ['dofpair',['DoFPair',['../structinternal_1_1MGTransfer_1_1DoFPair.html',1,'internal::MGTransfer']]],
  ['dofprintsolverstep',['DoFPrintSolverStep',['../classDoFPrintSolverStep.html',1,'']]],
  ['dot',['Dot',['../structinternal_1_1VectorOperations_1_1Dot.html',1,'internal::VectorOperations']]],
  ['dotproduct',['DotProduct',['../structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1DotProduct.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['double',['Double',['../classPatterns_1_1Double.html',1,'Patterns']]],
  ['double_5fcontraction_5fresult',['double_contraction_result',['../structinternal_1_1SymmetricTensorAccessors_1_1double__contraction__result.html',1,'internal::SymmetricTensorAccessors']]],
  ['double_5fcontraction_5fresult_3c_202_2c_202_2c_20dim_2c_20number_2c_20othernumber_20_3e',['double_contraction_result&lt; 2, 2, dim, Number, OtherNumber &gt;',['../structinternal_1_1SymmetricTensorAccessors_1_1double__contraction__result_3_012_00_012_00_01dim_bde24087db8a52ec06f500b41dd95304.html',1,'internal::SymmetricTensorAccessors']]],
  ['duplicatedcommunicator',['DuplicatedCommunicator',['../classUtilities_1_1MPI_1_1DuplicatedCommunicator.html',1,'Utilities::MPI']]],
  ['dx',['DX',['../structGridOutFlags_1_1DX.html',1,'GridOutFlags']]],
  ['dxflags',['DXFlags',['../structDataOutBase_1_1DXFlags.html',1,'DataOutBase']]],
  ['dynamicsparsitypattern',['DynamicSparsityPattern',['../classDynamicSparsityPattern.html',1,'']]]
];
