var searchData=
[
  ['c_2b_2b_2eh',['c++.h',['../c_09_09_8h.html',1,'']]],
  ['cell_5fdata_5ftransfer_2ecc',['cell_data_transfer.cc',['../distributed_2cell__data__transfer_8cc.html',1,'(Global Namespace)'],['../numerics_2cell__data__transfer_8cc.html',1,'(Global Namespace)']]],
  ['cell_5fdata_5ftransfer_2ecc_2eo_2ed',['cell_data_transfer.cc.o.d',['../distributed_2CMakeFiles_2obj__distributed__release_8dir_2cell__data__transfer_8cc_8o_8d.html',1,'(Global Namespace)'],['../numerics_2CMakeFiles_2obj__numerics__release_8dir_2cell__data__transfer_8cc_8o_8d.html',1,'(Global Namespace)']]],
  ['cell_5fdata_5ftransfer_2eh',['cell_data_transfer.h',['../distributed_2cell__data__transfer_8h.html',1,'(Global Namespace)'],['../numerics_2cell__data__transfer_8h.html',1,'(Global Namespace)']]],
  ['cell_5fid_2ecc',['cell_id.cc',['../cell__id_8cc.html',1,'']]],
  ['cell_5fid_2ecc_2eo_2ed',['cell_id.cc.o.d',['../cell__id_8cc_8o_8d.html',1,'']]],
  ['cell_5fid_2eh',['cell_id.h',['../cell__id_8h.html',1,'']]],
  ['cell_5fweights_2ecc',['cell_weights.cc',['../cell__weights_8cc.html',1,'']]],
  ['cell_5fweights_2ecc_2eo_2ed',['cell_weights.cc.o.d',['../cell__weights_8cc_8o_8d.html',1,'']]],
  ['cell_5fweights_2eh',['cell_weights.h',['../cell__weights_8h.html',1,'']]],
  ['changes_2eh',['changes.h',['../changes_8h.html',1,'']]],
  ['chunk_5fsparse_5fmatrix_2ecc',['chunk_sparse_matrix.cc',['../chunk__sparse__matrix_8cc.html',1,'']]],
  ['chunk_5fsparse_5fmatrix_2ecc_2eo_2ed',['chunk_sparse_matrix.cc.o.d',['../chunk__sparse__matrix_8cc_8o_8d.html',1,'']]],
  ['chunk_5fsparse_5fmatrix_2eh',['chunk_sparse_matrix.h',['../chunk__sparse__matrix_8h.html',1,'']]],
  ['chunk_5fsparsity_5fpattern_2ecc',['chunk_sparsity_pattern.cc',['../chunk__sparsity__pattern_8cc.html',1,'']]],
  ['chunk_5fsparsity_5fpattern_2ecc_2eo_2ed',['chunk_sparsity_pattern.cc.o.d',['../chunk__sparsity__pattern_8cc_8o_8d.html',1,'']]],
  ['chunk_5fsparsity_5fpattern_2eh',['chunk_sparsity_pattern.h',['../chunk__sparsity__pattern_8h.html',1,'']]],
  ['cmath_2eh',['cmath.h',['../cmath_8h.html',1,'']]],
  ['code_2dgallery_2eh',['code-gallery.h',['../code-gallery_8h.html',1,'']]],
  ['coding_5fconventions_2eh',['coding_conventions.h',['../coding__conventions_8h.html',1,'']]],
  ['collection_2eh',['collection.h',['../collection_8h.html',1,'']]],
  ['communication_5fpattern_5fbase_2eh',['communication_pattern_base.h',['../base_2communication__pattern__base_8h.html',1,'(Global Namespace)'],['../lac_2communication__pattern__base_8h.html',1,'(Global Namespace)']]],
  ['complex_5foverloads_2eh',['complex_overloads.h',['../complex__overloads_8h.html',1,'']]],
  ['component_5fmask_2ecc',['component_mask.cc',['../component__mask_8cc.html',1,'']]],
  ['component_5fmask_2ecc_2eo_2ed',['component_mask.cc.o.d',['../component__mask_8cc_8o_8d.html',1,'']]],
  ['component_5fmask_2eh',['component_mask.h',['../component__mask_8h.html',1,'']]],
  ['composition_5fmanifold_2eh',['composition_manifold.h',['../composition__manifold_8h.html',1,'']]],
  ['concepts_2eh',['concepts.h',['../concepts_8h.html',1,'']]],
  ['conditional_5fostream_2ecc',['conditional_ostream.cc',['../conditional__ostream_8cc.html',1,'']]],
  ['conditional_5fostream_2ecc_2eo_2ed',['conditional_ostream.cc.o.d',['../conditional__ostream_8cc_8o_8d.html',1,'']]],
  ['conditional_5fostream_2eh',['conditional_ostream.h',['../conditional__ostream_8h.html',1,'']]],
  ['config_2eh',['config.h',['../config_8h.html',1,'']]],
  ['connectivity_2eh',['connectivity.h',['../connectivity_8h.html',1,'']]],
  ['constrained_5flinear_5foperator_2eh',['constrained_linear_operator.h',['../constrained__linear__operator_8h.html',1,'']]],
  ['constraint_5fmatrix_2eh',['constraint_matrix.h',['../constraint__matrix_8h.html',1,'']]],
  ['constraints_2eh',['constraints.h',['../constraints_8h.html',1,'']]],
  ['convergence_5ftable_2ecc',['convergence_table.cc',['../convergence__table_8cc.html',1,'']]],
  ['convergence_5ftable_2ecc_2eo_2ed',['convergence_table.cc.o.d',['../convergence__table_8cc_8o_8d.html',1,'']]],
  ['convergence_5ftable_2eh',['convergence_table.h',['../convergence__table_8h.html',1,'']]],
  ['copy_5fdata_2eh',['copy_data.h',['../copy__data_8h.html',1,'']]],
  ['coupling_2ecc',['coupling.cc',['../coupling_8cc.html',1,'']]],
  ['coupling_2ecc_2eo_2ed',['coupling.cc.o.d',['../coupling_8cc_8o_8d.html',1,'']]],
  ['coupling_2eh',['coupling.h',['../coupling_8h.html',1,'']]],
  ['cuda_2eh',['cuda.h',['../doc_2doxygen_2headers_2cuda_8h.html',1,'(Global Namespace)'],['../include_2deal_8II_2base_2cuda_8h.html',1,'(Global Namespace)']]],
  ['cuda_5fatomic_2eh',['cuda_atomic.h',['../cuda__atomic_8h.html',1,'']]],
  ['cuda_5ffe_5fevaluation_2eh',['cuda_fe_evaluation.h',['../cuda__fe__evaluation_8h.html',1,'']]],
  ['cuda_5fhanging_5fnodes_5finternal_2eh',['cuda_hanging_nodes_internal.h',['../cuda__hanging__nodes__internal_8h.html',1,'']]],
  ['cuda_5fkernels_2eh',['cuda_kernels.h',['../cuda__kernels_8h.html',1,'']]],
  ['cuda_5fmatrix_5ffree_2eh',['cuda_matrix_free.h',['../cuda__matrix__free_8h.html',1,'']]],
  ['cuda_5fprecondition_2eh',['cuda_precondition.h',['../cuda__precondition_8h.html',1,'']]],
  ['cuda_5fsize_2eh',['cuda_size.h',['../cuda__size_8h.html',1,'']]],
  ['cuda_5fsolver_5fdirect_2eh',['cuda_solver_direct.h',['../cuda__solver__direct_8h.html',1,'']]],
  ['cuda_5fsparse_5fmatrix_2eh',['cuda_sparse_matrix.h',['../cuda__sparse__matrix_8h.html',1,'']]],
  ['cuda_5ftensor_5fproduct_5fkernels_2eh',['cuda_tensor_product_kernels.h',['../cuda__tensor__product__kernels_8h.html',1,'']]],
  ['cuda_5fvector_2eh',['cuda_vector.h',['../cuda__vector_8h.html',1,'']]]
];
