var searchData=
[
  ['general_5fdata_5fstorage_2eh',['general_data_storage.h',['../general__data__storage_8h.html',1,'']]],
  ['generators_2eh',['generators.h',['../generators_8h.html',1,'']]],
  ['generic_5flinear_5falgebra_2eh',['generic_linear_algebra.h',['../generic__linear__algebra_8h.html',1,'']]],
  ['geodynamics_2eh',['geodynamics.h',['../geodynamics_8h.html',1,'']]],
  ['geometric_5futilities_2ecc',['geometric_utilities.cc',['../geometric__utilities_8cc.html',1,'']]],
  ['geometric_5futilities_2eh',['geometric_utilities.h',['../geometric__utilities_8h.html',1,'']]],
  ['geometry_5fand_5fprimitives_2eh',['geometry_and_primitives.h',['../geometry__and__primitives_8h.html',1,'']]],
  ['geometry_5finfo_2ecc',['geometry_info.cc',['../geometry__info_8cc.html',1,'']]],
  ['geometry_5finfo_2eh',['geometry_info.h',['../geometry__info_8h.html',1,'']]],
  ['ginkgo_5fsolver_2ecc',['ginkgo_solver.cc',['../ginkgo__solver_8cc.html',1,'']]],
  ['ginkgo_5fsolver_2eh',['ginkgo_solver.h',['../ginkgo__solver_8h.html',1,'']]],
  ['global_5fdof_5findex_2eh',['global_dof_index.h',['../global__dof__index_8h.html',1,'']]],
  ['glossary_2eh',['glossary.h',['../glossary_8h.html',1,'']]],
  ['grad_5fdiv_2eh',['grad_div.h',['../grad__div_8h.html',1,'']]],
  ['graph_5fcoloring_2ecc',['graph_coloring.cc',['../graph__coloring_8cc.html',1,'']]],
  ['graph_5fcoloring_2eh',['graph_coloring.h',['../graph__coloring_8h.html',1,'']]],
  ['grid_2eh',['grid.h',['../grid_8h.html',1,'']]],
  ['grid_5fgenerator_2eh',['grid_generator.h',['../grid__generator_8h.html',1,'']]],
  ['grid_5fin_2eh',['grid_in.h',['../grid__in_8h.html',1,'']]],
  ['grid_5fout_2eh',['grid_out.h',['../grid__out_8h.html',1,'']]],
  ['grid_5frefinement_2eh',['grid_refinement.h',['../distributed_2grid__refinement_8h.html',1,'(Global Namespace)'],['../grid_2grid__refinement_8h.html',1,'(Global Namespace)']]],
  ['grid_5freordering_2eh',['grid_reordering.h',['../grid__reordering_8h.html',1,'']]],
  ['grid_5ftools_2eh',['grid_tools.h',['../grid__tools_8h.html',1,'']]],
  ['grid_5ftools_5fcache_2eh',['grid_tools_cache.h',['../grid__tools__cache_8h.html',1,'']]],
  ['grid_5ftools_5fcache_5fupdate_5fflags_2eh',['grid_tools_cache_update_flags.h',['../grid__tools__cache__update__flags_8h.html',1,'']]]
];
