name: Ubuntu

on:
  push:
    branches:
      - master
      - main
      - make_mini
  pull_request:
    branches:
      - master
      - main
      - make_mini

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: download and setup of dealii
        run: |
         #git clone https://github.com/dealii/dealii.git
         cp -rf ~/dealii-download/dealii .
         cd dealii
         git reset --hard aba0ae59325f68fc30465bca96fbb5585347a2fd
         ./contrib/utilities/download_clang_format
         mkdir ../Origin_file
         mv examples ../Origin_file
         cp -rf ../Translator_file/examples .
         mv include/deal.II ../Origin_file
         cp -rf ../Translator_file/deal.II include/
         mv doc/doxygen/headers ../Origin_file
         cp -rf ../Translator_file/headers doc/doxygen/
         cp -rf ../tests/* tests/

         

 
      - name: configure
        run: |
         cd dealii
         cmake -D CMAKE_BUILD_TYPE=Debug  -DDEAL_II_COMPONENT_DOCUMENTATION=ON -DDEAL_II_DOXYGEN_USE_MATHJAX=ON  .


      - name: build
        run: |
         cd dealii
         make -j 48
         #make documentation


      - name: Publish Doxygen documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dealii/doc
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true
          publish_branch: gh-pages

      - name: test
        run: |
          cd dealii
          make setup_tests_hello
          make setup_tests_mystl_test
          ctest 

      # - name: collect code coverage
      # run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"



